export const FETCH_BOOKS_REQUESTED = 'FETCH_BOOKS_REQUESTED';
export const FETCH_BOOKS_SUCCEEDED = 'FETCH_BOOKS_SUCCEEDED';
export const FETCH_BOOKS_FAILED = 'FETCH_BOOKS_FAILED';

export const CREATE_BOOK_REQUESTED = 'CREATE_BOOK_REQUESTED';
export const CREATE_BOOK_SUCCEEDED = 'CREATE_BOOK_SUCCEEDED';
export const CREATE_BOOK_FAILED = 'CREATE_BOOK_FAILED';
